const Translater = {
    data: {
        open: "Открытая",
        brick: "Кирпичн",
        monolithBrick: "Монолит/кирпич",
        monolith: "Монолит",
        panel: "Панель",
        commercialLandRent: "Коммерческий участок",
        commercialLandSale: "Коммерческий участок",
        office: "Офисное помещение",
        officeRent: "Офисное помещение",
        officeSale: "Офисное помещение",
        warehouse: "Складское помещение",
        warehouseRent: "Складское помещение",
        warehouseSale: "Складское помещение",
        shoppingArea: "Торговая площадь",
        floorSpace: "Торговая площадь",
        garageRent: "Гараж",
        garage: "Гараж",
        garageSale: "Гараж",
        shoppingAreaRent: "Торговая площадь",
        shoppingAreaSale: "Торговая площадь",
        production: "Производство",
        industry: "Производство",
        industryRent: "Производство",
        industrySale: "Производство",
        building: "Здание",
        buildingRent: "Здание",
        buildingSale: "Здание",
        freeAppointment: "Помещение свободного назначения",
        freeAppointmentObjectRent: "Помещение свободного назначения",
        freeAppointmentObjectSale: "Помещение свободного назначения",
        business: "Готовый бизнес",
        businessSale: "Готовый бизнес",
        rent: "аренда",
        sale: "продажа",
        rur: "руб.",
        squareMeter: "за метр",
        all: "за всю площадь",
        included: "включен",
        usn: "УСН",
        notIncluded: "не включен",
        monthly: "ежемесячно",
        annual: "ежегодно",
        longTerm: "на длительный срок",
        fewMonths: "на несколько месяцев",
        central: "центральное",
        autonomous: "автономное",
        ground: "наземная",
        underground: "подземная",
        hectare: "гектар",
        sotka: "сотка",
        multilevel: "Многоуровневая"
    },

    translate(enWord) {
        return this.data[enWord] || enWord;
    }
}

module.exports = Translater;